/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejemplotabla;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.axis.NumberAxis;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;

/**
 *
 * @author andresbaezrincon
 */
public class InterfazManual extends javax.swing.JFrame {
int Filas;
int Columnas;
int NumeroNotas;
   int fila=0;
    /**
     * Creates new form InterfazManual
     */
Estudiante est = new Estudiante();
    ArrayList<Estudiante> estudiantes = new ArrayList<Estudiante>();

    public InterfazManual() {
        initComponents();
        condicionesIniciales();
    }
   
    
            

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        txtNumeroEstudiantes = new javax.swing.JTextField();
        txtNumeronotas = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNota = new javax.swing.JTextField();
        txtNombreEstudiante = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lblNumero = new javax.swing.JLabel();
        btnIngresarNombre = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        lblNumeroNota = new javax.swing.JLabel();
        btnIngresarNota = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        btnGenerarPromedio = new javax.swing.JButton();
        btnMortalidad = new javax.swing.JButton();
        comboBox1 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnHistorico = new javax.swing.JButton();
        panelGrafico = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        btnExportar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Generar Tabla");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Numero Estudiantes");

        jLabel2.setText("Numero notas");

        jLabel3.setText("Nombre Estudiante");

        lblNumero.setText("1");

        btnIngresarNombre.setText("Ingresar");
        btnIngresarNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarNombreActionPerformed(evt);
            }
        });

        jLabel4.setText("Nota No.");

        lblNumeroNota.setText("1");

        btnIngresarNota.setText("Ingresar");
        btnIngresarNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarNotaActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        btnGenerarPromedio.setText("Generar Tabla de Promedios");
        btnGenerarPromedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarPromedioActionPerformed(evt);
            }
        });

        btnMortalidad.setText("Mortalidad");
        btnMortalidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMortalidadActionPerformed(evt);
            }
        });

        comboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBox1ActionPerformed(evt);
            }
        });

        jLabel5.setText("Graficar Histórico de Notas:");

        jLabel6.setText("Seleccione el nombre del Estudiante:");

        btnHistorico.setText("Mostrar Histórico");
        btnHistorico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistoricoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelGraficoLayout = new javax.swing.GroupLayout(panelGrafico);
        panelGrafico.setLayout(panelGraficoLayout);
        panelGraficoLayout.setHorizontalGroup(
            panelGraficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 326, Short.MAX_VALUE)
        );
        panelGraficoLayout.setVerticalGroup(
            panelGraficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 212, Short.MAX_VALUE)
        );

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel7.setText("HISTORICO DE NOTAS");

        jButton4.setText("Volver al Menú Principal");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        btnExportar.setText("Exportar CSV");
        btnExportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNumeronotas)
                            .addComponent(txtNumeroEstudiantes, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblNumeroNota, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtNombreEstudiante, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                                        .addComponent(txtNota)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnIngresarNombre)
                                    .addComponent(btnIngresarNota))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btnGenerarPromedio))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnExportar)
                                    .addComponent(btnMortalidad))))
                        .addGap(18, 49, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(comboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnHistorico)))
                                .addGap(104, 104, 104))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(panelGrafico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(94, 94, 94))))))
            .addGroup(layout.createSequentialGroup()
                .addGap(485, 485, 485)
                .addComponent(jLabel7)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel7)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNumeroEstudiantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNumeronotas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(lblNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtNombreEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(lblNumeroNota))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnIngresarNombre)
                                .addGap(36, 36, 36)
                                .addComponent(btnIngresarNota)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(btnGenerarPromedio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnMortalidad)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnExportar)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(comboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnHistorico))
                                .addGap(18, 18, 18)
                                .addComponent(panelGrafico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton4))))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int filas = Integer.parseInt(txtNumeroEstudiantes.getText());
        int columnas = Integer.parseInt(txtNumeronotas.getText())+1;
        this.Filas=filas;
        this.Columnas=columnas+1;
        this.NumeroNotas=columnas-1;
        jTable1.setModel(new DefaultTableModel(filas,columnas));  
        JTableHeader head = jTable1.getTableHeader();
        TableColumnModel tcm = head.getColumnModel();
        for(int i=0;i<columnas;i++){
        TableColumn tabCM = tcm.getColumn(i);
        if(i==0)
        tabCM.setHeaderValue("Nombre");
        else
           tabCM.setHeaderValue("Nota "+i); 
        jTable1.repaint();
        }
        jLabel3.setVisible(true);
        jLabel4.setVisible(true);
        lblNumero.setVisible(true);
        lblNumeroNota.setVisible(true);
        txtNombreEstudiante.setVisible(true);
        txtNota.setVisible(true);
        jTable1.setVisible(true);
        btnIngresarNombre.setVisible(true);
        btnIngresarNota.setVisible(true);
        btnIngresarNota.setEnabled(false);
        jButton1.setEnabled(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnIngresarNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarNombreActionPerformed
        // TODO add your handling code here:
        btnIngresarNota.setEnabled(true);
        btnIngresarNombre.setEnabled(false);
       jTable1.setValueAt(txtNombreEstudiante.getText() , fila, 0);
       estudiantes.add(new Estudiante(txtNombreEstudiante.getText()));
       comboBox1.addItem(txtNombreEstudiante.getText());
    }//GEN-LAST:event_btnIngresarNombreActionPerformed

    private void btnIngresarNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarNotaActionPerformed
        // TODO add your handling code here:
        if(Float.parseFloat(txtNota.getText())>5 || Float.parseFloat(txtNota.getText())<0){
            JOptionPane.showMessageDialog(null, "NOTA NO VALIDA");
        }else{
        float nota = Float.parseFloat(txtNota.getText());
        estudiantes.get(Integer.parseInt(lblNumero.getText())-1).notas.add(nota);
        
        jTable1.setValueAt(txtNota.getText(), fila,Integer.parseInt(lblNumeroNota.getText()));
        
        lblNumeroNota.setText(String.valueOf(Integer.parseInt(lblNumeroNota.getText())+1));
        
        if(Integer.parseInt(lblNumeroNota.getText())==NumeroNotas+1){
        fila++;
        if(fila==Filas){
            btnIngresarNota.setEnabled(false);
            btnIngresarNombre.setEnabled(false);
            btnGenerarPromedio.setVisible(true);
            comboBox1.setVisible(true);
            jLabel5.setVisible(true);
            jLabel6.setVisible(true);
            btnHistorico.setVisible(true);
            btnExportar.setVisible(true);
        }
        lblNumeroNota.setText(String.valueOf(1));
        lblNumero.setText(String.valueOf(Integer.parseInt(lblNumero.getText())+1));
         btnIngresarNota.setEnabled(false);
         btnIngresarNombre.setEnabled(true);
        }
        }
    }//GEN-LAST:event_btnIngresarNotaActionPerformed

    private void btnGenerarPromedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarPromedioActionPerformed
        // TODO add your handling code here:
        jTable2.setVisible(true);
        btnMortalidad.setVisible(true);
        for(int index=0;index<estudiantes.size();index++){
            estudiantes.get(index).calculoPromedio();
            estudiantes.get(index).calculoEstado();
        }
        jTable2.setModel(new DefaultTableModel(Filas,3));  
        JTableHeader head = jTable2.getTableHeader();
        TableColumnModel tcm = head.getColumnModel();
        for(int i=0;i<3;i++){
        TableColumn tabCM = tcm.getColumn(i);
        if(i==0)
        tabCM.setHeaderValue("Nombre");
        else if(i==1)
           tabCM.setHeaderValue("Promedio"); 
        else
           tabCM.setHeaderValue("Estado"); 
        jTable2.repaint();
        for(int indice=0;indice<estudiantes.size();indice++){
            for(int j=0;j<3;j++){
                if(j==0)
                    jTable2.setValueAt(estudiantes.get(indice).nombre, indice, j);
                if(j==1)
                    jTable2.setValueAt(estudiantes.get(indice).promedio, indice, j);
                if(j==2)
                    jTable2.setValueAt(estudiantes.get(indice).Estado, indice, j);
            
        }
        }
        }
        
    }//GEN-LAST:event_btnGenerarPromedioActionPerformed

    private void btnMortalidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMortalidadActionPerformed
        // TODO add your handling code here:
        int aprobado = 0, reprobado=0;
        for(int i=0;i<estudiantes.size();i++){
            if(estudiantes.get(i).Estado.equals("Aprobado"))
                aprobado++;
            else
                reprobado++;
        }
                JOptionPane.showMessageDialog(null, "Aprobado: "+String.valueOf((aprobado*100)/estudiantes.size())+"%"+"\nReprobado: "+String.valueOf((reprobado*100)/estudiantes.size())+"%");
    }//GEN-LAST:event_btnMortalidadActionPerformed

    private void comboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBox1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_comboBox1ActionPerformed

    private void btnHistoricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistoricoActionPerformed
        // TODO add your handling code here:
        XYSeries serie = new XYSeries("Notas");
        int valor = comboBox1.getSelectedIndex();
        for(int i=0;i<NumeroNotas;i++){
           serie.add(i,estudiantes.get(valor).notas.get(i));
        }
        XYSeriesCollection dataSet =new XYSeriesCollection();
        dataSet.addSeries(serie);
        
        JFreeChart chart = ChartFactory.createXYLineChart(comboBox1.getSelectedItem().toString(), "No. Nota", "Nota", dataSet);
        ChartPanel panel = new ChartPanel(chart);
        panelGrafico.setLayout(new java.awt.BorderLayout());
        panelGrafico.add(panel);
        panelGrafico.validate();
    }//GEN-LAST:event_btnHistoricoActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        InterfazPrincipal interfaz = new InterfazPrincipal();
        interfaz.setVisible(true);
        InterfazManual inter = new InterfazManual();
        inter.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Guardar como...");
        int userSelection = fileChooser.showSaveDialog(this);
        if(userSelection == JFileChooser.APPROVE_OPTION){
            File fileToSave = fileChooser.getSelectedFile();
            //lets write to file
         
            try {
                  FileWriter fw = new FileWriter(fileToSave);
                BufferedWriter bw = new BufferedWriter(fw);
                for (int i = 0; i< jTable1.getRowCount(); i++) {
                    for (int j = 0; j < jTable1.getColumnCount(); j++) {
                        //write
                        bw.write(jTable1.getValueAt(i, j).toString()+";");
                    }
                    bw.newLine();//record per line 
                }
                JOptionPane.showMessageDialog(this, "EXPORTADO CON EXITO","INFORMATION",JOptionPane.INFORMATION_MESSAGE);
                bw.close();
                fw.close();
            } catch (IOException ex) {
               JOptionPane.showMessageDialog(this, "ERROR","ERROR MESSAGE",JOptionPane.ERROR_MESSAGE);
            }
            
            
        }
    }//GEN-LAST:event_btnExportarActionPerformed

    public void setEstudiantes(ArrayList<Estudiante> estudiantes) {
        this.estudiantes = estudiantes;
    }
    public void condicionesIniciales(){
        jTable1.setVisible(false);
        jTable2.setVisible(false);
        jLabel3.setVisible(false);
        jLabel4.setVisible(false);
        lblNumero.setVisible(false);
        lblNumeroNota.setVisible(false);
        txtNombreEstudiante.setVisible(false);
        txtNota.setVisible(false);
        btnIngresarNombre.setVisible(false);
        btnIngresarNota.setVisible(false);
        btnGenerarPromedio.setVisible(false);
        btnMortalidad.setVisible(false);
        jLabel5.setVisible(false);
        jLabel6.setVisible(false);
        btnHistorico.setVisible(false);
        comboBox1.setVisible(false);
        btnExportar.setVisible(false);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazManual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazManual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazManual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazManual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazManual().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExportar;
    private javax.swing.JButton btnGenerarPromedio;
    private javax.swing.JButton btnHistorico;
    private javax.swing.JButton btnIngresarNombre;
    private javax.swing.JButton btnIngresarNota;
    private javax.swing.JButton btnMortalidad;
    private javax.swing.JComboBox<String> comboBox1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblNumeroNota;
    private javax.swing.JPanel panelGrafico;
    private javax.swing.JTextField txtNombreEstudiante;
    private javax.swing.JTextField txtNota;
    private javax.swing.JTextField txtNumeroEstudiantes;
    private javax.swing.JTextField txtNumeronotas;
    // End of variables declaration//GEN-END:variables
}
